### ISSUE TITLE
Python Tutorial: Conda Environment Issue with BHTSNE Module

### ISSUE THREAD

**Issue by JensBlack** [YttriLab/B-SOID#9]
Great work porting bsoid to python! Really, really thrilled to try it out!

 Unfortunately the module BHTSNE cannot be installed at the moment ( at least in my case). In your tutorial video/gif, you are actually not adding it in the command line, is there a reason?
The following error pops up when using (after successfully creating the new environment and installing ipython)
`pip install pandas tqdm matplotlib opencv-python seaborn scikit-learn bhtsne` :

```
Collecting pandas
  Using cached pandas-1.0.3-cp38-cp38-win_amd64.whl (8.9 MB)
Collecting tqdm
  Using cached tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
Collecting matplotlib
  Using cached matplotlib-3.2.1-cp38-cp38-win_amd64.whl (9.2 MB)
Collecting opencv-python
  Using cached opencv_python-4.2.0.34-cp38-cp38-win_amd64.whl (33.1 MB)
Collecting seaborn
  Using cached seaborn-0.10.1-py3-none-any.whl (215 kB)
Collecting scikit-learn
  Using cached scikit_learn-0.22.2.post1-cp38-cp38-win_amd64.whl (6.6 MB)
Collecting bhtsne
  Using cached bhtsne-0.1.9.tar.gz (86 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\envs\bsoid\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-_9m_4o00\\bhtsne\\setup.py'"'"'; __file__='"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-_9m_4o00\\bhtsne\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\schwa\AppData\Local\Temp\pip-install-_9m_4o00\bhtsne\pip-egg-info'
         cwd: C:\Users\schwa\AppData\Local\Temp\pip-install-_9m_4o00\bhtsne\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\schwa\AppData\Local\Temp\pip-install-_9m_4o00\bhtsne\setup.py", line 4, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

After installing Cython with `pip install cython` the following error is produced:

```
Collecting pandas
  Using cached pandas-1.0.3-cp38-cp38-win_amd64.whl (8.9 MB)
Collecting tqdm
  Using cached tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
Collecting matplotlib
  Using cached matplotlib-3.2.1-cp38-cp38-win_amd64.whl (9.2 MB)
Collecting opencv-python
  Using cached opencv_python-4.2.0.34-cp38-cp38-win_amd64.whl (33.1 MB)
Collecting seaborn
  Using cached seaborn-0.10.1-py3-none-any.whl (215 kB)
Collecting scikit-learn
  Using cached scikit_learn-0.22.2.post1-cp38-cp38-win_amd64.whl (6.6 MB)
Collecting bhtsne
  Using cached bhtsne-0.1.9.tar.gz (86 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\envs\bsoid\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-ya4007uh\\bhtsne\\setup.py'"'"'; __file__='"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-ya4007uh\\bhtsne\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\schwa\AppData\Local\Temp\pip-install-ya4007uh\bhtsne\pip-egg-info'
         cwd: C:\Users\schwa\AppData\Local\Temp\pip-install-ya4007uh\bhtsne\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\schwa\AppData\Local\Temp\pip-install-ya4007uh\bhtsne\setup.py", line 5, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Splitting up the pip install in `pip install pandas tqdm matplotlib opencv-python seaborn scikit-learn` and `pip install bhtsne` solves the issue, but raises a new error:

```
(bsoid) C:\Users\schwa>pip install bhtsne
Collecting bhtsne
  Using cached bhtsne-0.1.9.tar.gz (86 kB)
Requirement already satisfied: numpy in d:\anaconda\envs\bsoid\lib\site-packages (from bhtsne) (1.18.3)
Requirement already satisfied: cython in d:\anaconda\envs\bsoid\lib\site-packages (from bhtsne) (0.29.17)
Building wheels for collected packages: bhtsne
  Building wheel for bhtsne (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Anaconda\envs\bsoid\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-4ha89yy6\\bhtsne\\setup.py'"'"'; __file__='"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-4ha89yy6\\bhtsne\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\schwa\AppData\Local\Temp\pip-wheel-r3sbhgc2'
       cwd: C:\Users\schwa\AppData\Local\Temp\pip-install-4ha89yy6\bhtsne\
  Complete output (12 lines):
  D:\Anaconda\envs\bsoid\lib\distutils\extension.py:131: UserWarning: Unknown Extension options: 'extra_compile_flags'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\bhtsne
  copying bhtsne\__init__.py -> build\lib.win-amd64-3.8\bhtsne
  running build_ext
  building 'bhtsne_wrapper' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for bhtsne
  Running setup.py clean for bhtsne
Failed to build bhtsne
Installing collected packages: bhtsne
    Running setup.py install for bhtsne ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\envs\bsoid\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-4ha89yy6\\bhtsne\\setup.py'"'"'; __file__='"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-4ha89yy6\\bhtsne\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\schwa\AppData\Local\Temp\pip-record-bqx3h2oo\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda\envs\bsoid\Include\bhtsne'
         cwd: C:\Users\schwa\AppData\Local\Temp\pip-install-4ha89yy6\bhtsne\
    Complete output (12 lines):
    D:\Anaconda\envs\bsoid\lib\distutils\extension.py:131: UserWarning: Unknown Extension options: 'extra_compile_flags'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\bhtsne
    copying bhtsne\__init__.py -> build\lib.win-amd64-3.8\bhtsne
    running build_ext
    building 'bhtsne_wrapper' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda\envs\bsoid\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-4ha89yy6\\bhtsne\\setup.py'"'"'; __file__='"'"'C:\\Users\\schwa\\AppData\\Local\\Temp\\pip-install-4ha89yy6\\bhtsne\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\schwa\AppData\Local\Temp\pip-record-bqx3h2oo\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda\envs\bsoid\Include\bhtsne' Check the logs for full command output.
```
This seems to be a known but unsolved issue with [bhtsne ](https://github.com/dominiek/python-bhtsne/issues/8). I am wondering if you encountered the same issues?

Here is my `conda list`:

```
# packages in environment at D:\Anaconda\envs\bsoid:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                    py38_0
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py38_0
colorama                  0.4.3                      py_0
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.17                  pypi_0    pypi
decorator                 4.4.2                      py_0
ipython                   7.13.0           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
jedi                      0.17.0                   py38_0
joblib                    0.14.1                   pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
numpy                     1.18.3                   pypi_0    pypi
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1g               he774522_0
pandas                    1.0.3                    pypi_0    pypi
parso                     0.7.0                      py_0
pickleshare               0.7.5                 py38_1000
pip                       20.0.2                   py38_1
prompt-toolkit            3.0.4                      py_0
prompt_toolkit            3.0.4                         0
pygments                  2.6.1                      py_0
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.8.2               h5fd99cc_11
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.10.1                   pypi_0    pypi
setuptools                46.1.3                   py38_0
six                       1.14.0                   py38_0
sqlite                    3.31.1               h2a8f88b_1
tqdm                      4.45.0                   pypi_0    pypi
traitlets                 4.3.3                    py38_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.9                      py_0
wheel                     0.34.2                   py38_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4
```

**Comment by JensBlack** [comment]
I get the same error when installing everything in
Python 2.7 (as expected)
Python 3.5.6

**Comment by JensBlack** [comment]
Installing the visual c++ build tools as suggested [here](https://github.com/benfred/implicit/issues/76) solved the issue (after a restart).
Link to Download on Microsoft Website: [Direct](https://visualstudio.microsoft.com/de/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) | [Indirect](https://visualstudio.microsoft.com/de/downloads/)


```
(bsoid) C:\Users\schwa\PycharmProjects\B-SOID>pip install bhtsne
Collecting bhtsne
  Using cached bhtsne-0.1.9.tar.gz (86 kB)
Requirement already satisfied: numpy in d:\anaconda\envs\bsoid\lib\site-packages (from bhtsne) (1.18.3)
Requirement already satisfied: cython in d:\anaconda\envs\bsoid\lib\site-packages (from bhtsne) (0.29.17)
Building wheels for collected packages: bhtsne
  Building wheel for bhtsne (setup.py) ... done
  Created wheel for bhtsne: filename=bhtsne-0.1.9-cp38-cp38-win_amd64.whl size=52094 sha256=645a102d4b8ff661b216c0542c5735e1e09944ec5ef916d5bd091ce677836aa1
  Stored in directory: c:\users\schwa\appdata\local\pip\cache\wheels\aa\c7\a8\6d827fea433c4238dad92d6012d1f5249e8af6e7cf020cabe1
Successfully built bhtsne
Installing collected packages: bhtsne
Successfully installed bhtsne-0.1.9
```
